CONTAINER toscillator
{
	NAME toscillator;
	INCLUDE Texpression;

	GROUP ID_TAGPROPERTIES
	{
		BITMAPBUTTON OSC_WAVEFORMPREVIEW { };
		LONG OSC_FUNCTION
		{
			CYCLE
			{
				FUNC_SINE;
				FUNC_COSINE;
				FUNC_TRIANGLE;
				FUNC_SAWTOOTH;
				FUNC_SQUARE;
				FUNC_PULSE;
				FUNC_PULSERND;
				-1;
				FUNC_SAW_ANALOG;
				FUNC_SHARKTOOTH_ANALOG;
				FUNC_SQUARE_ANALOG;
				FUNC_ANALOG;
				-1;
				FUNC_CUSTOM;
			}
		}
		LONG OSC_RANGE
		{
			CYCLE
			{
				RANGE_01;
				RANGE_11;
			}
		}
		BOOL OSC_INVERT {  }
		SPLINE OSC_CUSTOMFUNC
		{
			HIDDEN;
			INPORT;

			SHOWGRID_H;
			SHOWGRID_V;

			MINSIZE_H 100;
			MINSIZE_V 90;

			EDIT_H;
			EDIT_V;

			X_MIN 0.0;
			X_MAX 1.0;

			Y_MIN 0.0;
			Y_MAX 1.0;

			X_STEPS 0.1;
			Y_STEPS 0.1;

			OPTIMAL_X_MIN 0.0;
			OPTIMAL_X_MAX 1.0;
			OPTIMAL_Y_MIN 0.0;
			OPTIMAL_Y_MAX 1.0;

			USE_OPTIMAL_RANGE;
		}

		REAL OSC_INPUTSCALE	 { INPORT; EDITPORT; UNIT PERCENT; MIN 0.0; STEP 0.1; }
		REAL OSC_PULSEWIDTH { INPORT; EDITPORT; UNIT REAL; MIN 0.0; MAX 1.0; STEP 0.001; }
		LONG OSC_HARMONICS { INPORT; EDITPORT; MIN 1; }
		REAL OSC_HARMONICS_INTERVAL { INPORT; EDITPORT; UNIT REAL; MIN 0.1; STEP 0.1; }
		REAL OSC_HARMONICS_OFFSET { INPORT; EDITPORT; UNIT REAL; STEP 0.1; }

		SEPARATOR { LINE; }

		BOOL OSCTAG_OUTPUT_POS_ENABLE { }
		VECTOR OSCTAG_OUTPUT_POS { UNIT METER; }
		BOOL OSCTAG_OUTPUT_SCALE_ENABLE { }
		VECTOR OSCTAG_OUTPUT_SCALE { UNIT PERCENT; }
		BOOL OSCTAG_OUTPUT_ROT_ENABLE { }
		VECTOR OSCTAG_OUTPUT_ROT { UNIT DEGREE; }
	}
}
