#ifndef C4D_SYMBOLS_H__
#define C4D_SYMBOLS_H__

enum
{
	IDS_OSCILLATORNODE	= 10000,
	IDS_OSCILLATOR_NODEGROUP,

	IDS_FUNC_SINE,
	IDS_FUNC_COSINE,
	IDS_FUNC_TRIANGLE,
	IDS_FUNC_SQUARE,
	IDS_FUNC_SAWTOOTH,
	IDS_FUNC_PULSE,
	IDS_FUNC_PULSERND,
	IDS_FUNC_SAW_ANALOG,
	IDS_FUNC_SHARKTOOTH_ANALOG,
	IDS_FUNC_CUSTOM,

	_DUMMY_ELEMENT_
};

#endif // C4D_SYMBOLS_H__
